### ISSUE TITLE
NuGet package for timrlink.net.Core

### ISSUE THREAD

**Issue by AlexZeitler** [troii/timrlink.net#13]
Hi, I would appreciate if you could also provide a NuGet package for `timrlink.net.Core`.

**Comment by daberni** [comment]
Hi Alex,

thank you for your interest and sorry for the late answer. Sadly there is no plan of providing `timrlink.net.Core` as a Nuget package.

We are currently in the process of developing a new restful API for our timr services which is planned to replace the existing timrsync SOAP API in the long term. Anyway we will still provide support for the existing SOAP API but will not provide any new features as soon as the new restful API is publicly available.

We are planning to provide an OpenAPI Spec and generated clients, including a .Net client as nuget Package, for the new restful API which should probably meet your needs.

We will come back to you as soon as these are available. Sadly, there is currently no fixed timeline available as when this will be the case.

If you are interested in beta testing the new restful API you can write an email to info@timr.com and we will come back to you as soon as there is more information about it.

**Comment by AlexZeitler** [comment]
@daberni Thanks, I've send an email our sales contact at timr.
